version: '3'

services:
  postgres:
    image: postgres:14.4-alpine
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    ports:
      - 5435:5432
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: robotland
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: robotland-db
